# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-02 15:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars_project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='org',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cars_project.Dealership'),
        ),
    ]
