# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-26 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_project', '0002_auto_20180124_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_img',
            field=models.ImageField(default='cars_project/car_foto/no_img.png', upload_to='cars_project/car_foto'),
        ),
    ]
