# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-15 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars_project', '0008_auto_20180211_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealership',
            name='logo',
            field=models.ImageField(default='cars_project/car_logo/no-logo-available.gif', upload_to='cars_project/logo'),
        ),
    ]
